package com.acme.sales.model.tests.repo;

import com.acme.infra.postgresql.JDBCBase;

import java.sql.*;

/**
 * This is to demonstrate the working of the JDBC Repo
 *
 * 1. Create a Test table by copying pasting the following SQL in the PostgreSQL
 *    browser
         CREATE TABLE person (
         person_id     INT  generated by default as identity,
         name          VARCHAR(255 ) not null,
         age           INT not null,
         PRIMARY   KEY(person_id)
         );
 * 2. Change the main function to add a few persons
 * 3. Change the argument for getting the information on the persons
 *
 * SQLException => Indicates one of the following:
 * 1. The credentials or host information you have provided in JDBCBase is bad
 * 2. Your machine is UNABLE to reach the PostgreSQL host - please go through exception details
 */
public class JDBCRepoTestTxnal extends JDBCBase  {

    public static void main(String[] args) throws Exception {
//        String personIdJSON = insertPerson("rajan",22);
//        System.out.println("Inserted = "+personIdJSON);
//
//        personIdJSON = insertPerson("jane",29);
//        System.out.println("Inserted = "+personIdJSON);
//
//        String result = selectPerson("jane");
//        System.out.println("Selected = "+ result);

//        String stmt1 = "INSERT INTO PERSON(name, age) VALUES('Jane', 43) RETURNING *";// person_id AS person_id";
//        String stmt2 = "INSERT INTO PERSON(name, age) VALUES('Mary', 72) ;//RETURNING person_id AS person_id";
//
//        ArrayList<String>  sqls = new ArrayList<>();
//        sqls.add(stmt1);
////        sqls.add(stmt2);
//
//        JDBCRepoTestTxnal repo = new JDBCRepoTestTxnal();
//
//        repo.executeSQL(sqls);


        // https://www.postgresql.org/docs/9.1/queries-with.html
        String query = "WITH proposal_event AS ( "+
        "INSERT INTO person(name,age) VALUES('jack',23) RETURNING person_id" +
        "), proposalevents as (" +
                "INSERT INTO proposalevents(event_guid,payload) VALUES('guid','payload')" +
                ")" +
        "SELECT person_id FROM proposal_event";


    }

    /**
     * This will insert a person in the test table - person
     */
    private static String insertPerson(String name, int age) throws SQLException {
        String sql = "INSERT INTO PERSON(name, age) VALUES(";
        sql += "'"+name+"', "+age+") RETURNING person_id AS person_id";

        System.out.println("SQL INSERT Statement="+sql);

        JDBCRepoTestTxnal repo = new JDBCRepoTestTxnal();
        return repo.executeSQLUpdate(sql);
    }


    private void test() throws SQLException {
        Connection connection = null;

        try {
            // 1. Create the connection to DB
            connection = DriverManager.getConnection(JDBC_URL, JDBC_USER, JDBC_PASSWORD);
            connection.setAutoCommit(false);

            String sql = "INSERT INTO PERSON(name, age) VALUES('Jane', 43) RESTURN *";
            Statement stmt = connection.prepareStatement(sql,Statement.RETURN_GENERATED_KEYS);

            stmt.executeBatch();

            ResultSet rs = stmt.getGeneratedKeys();
            System.out.println(stmt.getGeneratedKeys().getMetaData().getColumnCount());

            while(rs.next()){
                System.out.println("=>"+rs.getInt(1));
            }

            System.out.println("DONE");

            connection.commit();
        }catch (SQLException sqle){
            sqle.printStackTrace();
        }

    }




    /**
     * This will select the person from the test table person
     */
    private static String selectPerson(String name) throws SQLException {
        String sql = "SELECT * FROM PERSON WHERE ";
        sql += " name='"+name+"'";

        System.out.println("SQL SELECT Statement="+sql);

        JDBCRepoTestTxnal repo = new JDBCRepoTestTxnal();
        return repo.executeSQL(sql);
    }

}
