package com.acme.sales.model.tests.repo;

import com.acme.infra.postgresql.JDBCBase;

import java.sql.SQLException;

/**
 * This is to demonstrate the working of the JDBC Repo
 *
 * 1. Create a Test table by copying pasting the following SQL in the PostgreSQL
 *    browser
         CREATE TABLE person (
         person_id     INT  generated by default as identity,
         name          VARCHAR(255 ) not null,
         age           INT not null,
         PRIMARY   KEY(person_id)
         );
 * 2. Change the main function to add a few persons
 * 3. Change the argument for getting the information on the persons
 *
 * SQLException => Indicates one of the following:
 * 1. The credentials or host information you have provided in JDBCBase is bad
 * 2. Your machine is UNABLE to reach the PostgreSQL host - please go through exception details
 */
public class JDBCRepoTest extends JDBCBase  {

    public static void main(String[] args) throws Exception {
        String personIdJSON = insertPerson("rajan",22);
        System.out.println("Inserted = "+personIdJSON);

        personIdJSON = insertPerson("jane",29);
        System.out.println("Inserted = "+personIdJSON);

        String result = selectPerson("jane");
        System.out.println("Selected = "+ result);
    }

    /**
     * This will insert a person in the test table - person
     */
    private static String insertPerson(String name, int age) throws SQLException {
        String sql = "INSERT INTO PERSON(name, age) VALUES(";
        sql += "'"+name+"', "+age+") RETURNING person_id AS person_id";

        System.out.println("SQL INSERT Statement="+sql);

        JDBCRepoTest  repo = new JDBCRepoTest();
        return repo.executeSQLUpdate(sql);
    }

    /**
     * This will select the person from the test table person
     */
    private static String selectPerson(String name) throws SQLException {
        String sql = "SELECT * FROM PERSON WHERE ";
        sql += " name='"+name+"'";

        System.out.println("SQL SELECT Statement="+sql);

        JDBCRepoTest  repo = new JDBCRepoTest();
        return repo.executeSQL(sql);
    }


}
