@startuml
'https://plantuml.com/class-diagram

class Profile {
    - name

    + String name()
    + String department()
}

interface Employee {

    + double getProfile()

    + void calculatePay()

}

Employee --> Profile : creates instance of  1:1

class PartTimeEmployee implements Employee {

    + double getProfile()

    + void calculatePay()
}

class FullEmployee implements Employee {


    + double getProfile()

    + void calculatePay()
}

class ManagementEmployee extends FullEmployee {


    + double getProfile()

    + void calculatePay()
}

class Company {
  + Array  empList
  + Boolean addEmployee(Employee)  : Adds the employee to DB
  + Bolean removeEmployee(Employee) : removes empl

  - int find(Employee)
}

@enduml