@startuml

title    Payment Confirmation Class \n\n

'In Sales context this does not exist on its own
package com.acme.sales.model.payment {
    class PaymentConfirmation <<Value Object>> {
        + Date : processedDate
        + int  : confirmationReference
        + int  : cancellarionReference
    }
}
@enduml